package net.termer.twine.utils;

import java.util.ArrayList;

import io.vertx.core.json.JsonObject;
import net.termer.twine.ServerManager;

/**
 * Utility class for chaining callbacks rather than nesting them.
 * @author termer
 * @since 1.0-alpha
 */
public class Callback {
	private Throwable _cause = null;
	private JsonObject _data = new JsonObject();
	private ArrayList<CallbackAction> _callbacks = new ArrayList<CallbackAction>();
	private ArrayList<CallbackAction> _failCallbacks = new ArrayList<CallbackAction>();
	private int _execIndex = 0;
	private boolean _async = false;
	private boolean _running = false;
	
	/**
	 * Creates a new Callback object
	 * @since 1.0-alpha
	 */
	public Callback() {
		_async = false;
	}
	
	/**
	 * Creates a new Callback object
	 * @param async whether to run callbacks asynchronously rather than blocking. Keep in mind that this can greatly slow execution and is not generally recommended
	 * @since 1.0-alpha
	 */
	public Callback(boolean async) {
		_async = async;
	}
	
	/**
	 * Adds a callback
	 * @param action the callback
	 * @param fail the handler for any errors caught while executing the callback
	 * @return this Callback, to be used fluently
	 * @since 1.0-alpha
	 */
	public Callback then(CallbackAction action, CallbackAction fail) {
		_callbacks.add(action);
		_failCallbacks.add(fail);
		return this;
	}
	
	/**
	 * Returns data passed by other callbacks
	 * @return data passed by callbacks
	 * @since 1.0-alpha
	 */
	public JsonObject data() {
		return _data;
	}
	
	/**
	 * Passes a Throwable error and executes this callback's error handler.
	 * Calling fail().next() is permitted, so if you do not want the next callback to be executed, be sure to call end() in the failure callback.
	 * @param error the error that was caught
	 * @return this Callback, to be used fluently
	 * @since 1.0-alpha
	 */
	public Callback fail(Throwable error) {
		_cause = error;
		CallbackAction fail = _failCallbacks.get(_execIndex);
		if(_async && fail != null) {
			ServerManager.vertx().executeBlocking(f -> {
				fail.run(this);
			}, r -> {});
		} else if(fail == null) {
			_cause.printStackTrace();
		} else {
			fail.run(this);
		}
		
		return this;
	}
	
	/**
	 * Returns the Throwable passed by a fail() call in a callback. Null if none was passed
	 * @return The Throwable generated by a fail()
	 * @since 1.0-alpha
	 */
	public Throwable cause() {
		return _cause;
	}
	
	/**
	 * Returns whether callbacks are still running.
	 * Not that this may not be wholly accurate, as it only checks if end() or next() without a following callback has been called.
	 * @return whether callbacks are still running
	 * @since 1.0-alpha
	 */
	public boolean running() {
		return _running;
	}
	
	/**
	 * Executes the next callback, if any
	 * @return this Callback, to be used fluently
	 * @since 1.0-alpha
	 */
	public Callback next() {
		_execIndex++;
		if(_execIndex < _callbacks.size()) {
			CallbackAction cb = _callbacks.get(_execIndex);
			if(_async) {
				ServerManager.vertx().executeBlocking(f -> {
					try {
						cb.run(this);
					} catch(Exception e) {
						fail(e);
					}
				}, r -> {});
			} else {
				try {
					cb.run(this);
				} catch(Exception e) {
					fail(e);
				}
			}
		} else {
			_running = false;
		}
		return this;
	}
	
	/**
	 * Clears all callbacks and ends all further execution.
	 * Should be used on the last callback in chain, as it signifies that all callbacks are finished.
	 * @since 1.0-alpha
	 */
	public void end() {
		_callbacks.clear();
		_failCallbacks.clear();
		_execIndex = 0;
		_running = false;
	}
	
	/**
	 * Executes all callbacks
	 * @return this Callback, to be used fluently
	 * @since 1.0-alpha
	 */
	public Callback execute() {
		if(_callbacks.size() > 0) {
			_running = true;
			if(_async) {
				ServerManager.vertx().executeBlocking(f -> {
					_callbacks.get(0).run(this);
				}, r -> {});
			} else {
				_callbacks.get(0).run(this);
			}
		}
		return this;
	}
	
	/**
	 * Blocks the current thread until all callbacks are done executing.
	 * This may not be wholly accurate, as it only waits for an end() or a next() without a following callback.
	 * Every 10ms the method will check if callbacks are finished, and if not, will go to sleep for 10ms
	 * @return this Callback, to be used fluently
	 * @since 1.0-alpha
	 */
	public Callback await() {
		while(_running) {
			try {
				Thread.sleep(10);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
		}
		return this;
	}
	
	/**
	 * Simple interface for callbacks
	 * @author termer
	 * @since 1.0-alpha
	 */
	public interface CallbackAction {
		/**
		 * Performs an action
		 * @param cb the Callback object that's running this callback
		 * @since 1.0-alpha
		 */
		public void run(Callback cb);
	}
}